# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ownerInfo', models.TextField(blank=True, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=50, null=True)),
                ('contactTel', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.DateTimeField(auto_now_add=True)),
                ('leave', models.DateTimeField(blank=True, null=True)),
                ('receivingParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.CarOwner')),
            ],
        ),
        migrations.CreateModel(
            name='RegNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='reqNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.RegNumber'),
        ),
        migrations.AddField(
            model_name='autocard',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.CarColor'),
        ),
        migrations.AddField(
            model_name='autocard',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.CarModel'),
        ),
        migrations.AddField(
            model_name='autocard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.CarOwner'),
        ),
        migrations.AddField(
            model_name='autocard',
            name='regNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.RegNumber'),
        ),
        migrations.AlterUniqueTogether(
            name='autocard',
            unique_together=set([('id', 'regNumber')]),
        ),
    ]
