# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20170613_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='reqNumber',
            new_name='regNumber',
        ),
        migrations.RenameField(
            model_name='regnumber',
            old_name='reqNumber',
            new_name='regNumber',
        ),
    ]
