# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20170613_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='regNumber',
        ),
        migrations.AddField(
            model_name='entry',
            name='autoCad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parking.AutoCard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autocard',
            name='regNumber',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='RegNumber',
        ),
    ]
