# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20170613_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocard',
            name='regNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
